language: python
python:
- '2.7'
- '3.5'
branches:
  only:
  - master
  - develop
before_install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
install:
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    pip future pytest coverage pytest-cov numpy cython pandas scipy
- source activate test-environment
- pip install codecov
- pip install -e .
script:
- py.test --cov=genometools --cov-report=xml tests/
after_success:
- codecov
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: pypi
  user: flo-compbio
  distributions: sdist bdist_wheel
  password:
    secure: kd82WySn1oaYMDA8v1fMnebfJK4aLcqMKdYNgjFaJIyPYJKX7a4AKGbwxUA1UQeRDOQR4AWeYfJPnr/AV+DUmsiCkd5C9vomO0cQpqrR1qTe4p+1mB63qSM1gpeClZvUhRry1Tyz4HDct/mjThrgcLXZMT01I+5VPx46NPhWQrSY3b0UVS6XqxKD7DWa9AXPVbHpg0Ycrxe/0w4Lzlt5Cu9FS+8nMTu73ioc4c/VX7M3+WWTq90clGcdQm4vszdc2PTCNeDZweagUyKcrP4c19+1Re52zj933q8nx7UU7Z//88tlSL4flUcMM/7dep6/avRn39OWyEBvEUE+S0Gbc8mq0fj+98TnLbVUalCTA2M7Bv1EgbXQaABJXDH7MYD1JXjvUe1dIMT1eosldbmJfpCpcc/xdCa7l03OQygl1JgsD/DVrntb4fSEh+C0o6eTtUryrsvMinle5HwFra3KAf+3aXQGtGHtXW2V1U26N31Xky9YqCmwmg8G9UAzQqxciMWIZ72d2iHthQFB8bpn0oTz5hKz7uBZrLBBKvLTSF5n7QxdO1LcInY5zAy0zCeT2yw4d0QXcz7pDxVaoebTZ4sfq1bCfHpZfgOvZmxuo+ubC3y0/ZEcTJp5dXfHnrBJDwD6e2TKovy7iipczso9w8VPJ+HTabyDyQMiOTaCfj4=
>>>>>>> develop
  on:
    branch: master
    repo: flo-compbio/genometools
